### ISSUE TITLE
Update the LFE Style Guide

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#100]
Tasks:

* [ ] Migrate the old style guide content into the new dev site - #101
* [ ] Style Guide: Add Content to 6 Testing - #6
* [ ] Style Guide: Add Content to 7.3 Objects and State - #7
* [ ] Style Guide: Add Content to 8.2 EVAL-WHEN-COMPILE - #8
* [ ] Style Guide: Add Content to 12 Pitfalls - #5

Part of epic #98

**Comment by oubiwann** [comment]
Do this in guidebook instead.
