### ISSUE TITLE
Infrastructure Updates

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#102]
Features:

* [x] Replace bootstrap-sass with git submodule - #103
* [x] Add a file watcher - #106
  - [x] Recompile ErlyDTL files when they change - #107
  - [x] Recompile LFE files when they change - #108

Part of release #95
