### ISSUE TITLE
Deprecate docs.lfe.io in favour of books and lfe.io/docs

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#130]
This will be done in conjunction with the release of the updated LFE site here: https://github.com/lfe/lfe.github.io/issues/113

Additional features/tasks:
* [ ] Ensure all existing docs content exists elsewhere, in linkable form
* [x] https://github.com/lfe/lfe.github.io/issues/120
* [ ] Change docs.lfe.io to redirect to lfe.io/docs
* [ ] Move lfe/docs repo to lfe-deprecated/docs
* [ ] Archive lfe-deprecated/docs
