### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#66]
Features/Tasks:

* [x] Style docs.lfe.io to use the new theme - #65 
* [x] Templatize mockups/examples - lfe/docs3#11 
* [x] Explore the possibility of using a new set of fonts for the site - #88 
* [x] Update site styles to use new fonts - #89 
* [x] Support multiple deployments of CSS - #90 
* [x] Create a custom LFE Bootstrap theme - #92 

Part of Milestone v3  #62

**Comment by oubiwann** [comment]
Well, crap -- somehow the entire contents of this ticket were over-written by the contents of another ticket (#86). I'll search my emails to see if I can find the original text :-( I usually don't get messages when I'm the one updating the text, though ...

Oh, hey -- @rvirding, could you do me a favor? Could you search your email for "look and feel" and see if you can find the original description of this ticket? I think you might be subscribed to these changes ...

**Comment by oubiwann** [comment]
I've updated the ticket description with a list of tickets that were recorded as linking here ... best I can do for now to replace the lost content :-(

**Comment by oubiwann** [comment]
Closing for v3.0 release; moving uncompleted features/tasks into epic #96 of the v3.1 release.
