### ISSUE TITLE
Unification

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#69]
All of the various forms of documentation identified in ticket #63 need to be brought into the fold:

- [x] Use some form of configuration for page-building - https://github.com/lfe/docs3/issues/1
- [x] Come up with a re-direct plan for existing docs - #51 
- [x] Support generating pages with HTML fragments - #93

Part of Milestone v3  #62

**Comment by oubiwann** [comment]
Closing for v3.0 release; moving uncompleted features/tasks into epic #97 of the v3.1 release.
