### ISSUE TITLE
Publish Documentation to Github

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#86]
Features/Tasks:

* [x] [Select new platform for static generation](https://github.com/lfe/docs/issues/72) (part of [epic 64](https://github.com/lfe/docs/issues/64))
  - [x] Use the [poise](https://github.com/lfex/poise) LFE library
* [x] Create a data structure that pairs site paths to arbitrary functions (where the functions are responsible for ultimately generating the content that will be available at the corresponding paths) - https://github.com/lfex/poise/issues/1
* [x] Create a function that exports all the content defined in the data structure above to a given or configured directory - https://github.com/lfex/poise/issues/3
* [x] Support versioning of published docs (see #68)
* [x] Add the capability of serving pages locally during development - #94
* [x] Create site map for static file generation - #87
* [x] Use new Github support for publishing out of a project's `docs` dir
  * [x] Create docs dir
  * [x] Delete most of the old docs make targets
  * [x] Statically generate site to docs dir using poise
  * [x] Update static generation to account for current version and previous versions
* [x] Restructure `docs` dir in preparation for release 
  * [x] Add old versions of the site (these are all tagged) - this will require running Jekyll locally for each of these to convert the Markdown source to HTML
    * [x] v0.7
    * [x] v0.8
    * [x] v0.9
    * [x] v0.10
    * [x] Create a new tag for v1.2 (Aug 24, 2016) and then add the content
  * [x] Generate the new/dev content in dev
  * [x] Create explicit, step-by-step instructions for contributors to add new templates, pages, generated content, etc.
* [x] Perform clean-up tasks
  * [x] Remove theme drop-down from top-nav
  * [x] Update copyright years
  * [x] Diff dev lfe.css with SASS version and update SASS version with latest changes
  * [x] Visit all the pages in the v1.2 release and note any missing/incorrect bits
  * [x] Make notes here for all the missing bits
  * [x] Remove `old` dir
  * [x] Review the contents of all the LFE modules and make sure everything's still useful
  * [x] Update `docs` gen_server to run the latest code
  * [x] Update the README to point to the updated gen_server API  in `docs`
* [ ] Run in production - once all the content is generated in docs locally, it's time to go live (since this won't actually change the current docs site; it will be the same)
  * ~~Update the old index pages to include an "Update" link pointing to http://docs.lfe.io/dev for those interested in bleeding-edge docs~~ - WONTDO - the drop-down docs version menu handles this use case better
  * [x] Create new master branch in docs repo (it only has a gh-pages branch right now)
  * [x] Merge all of docs3 repo into docs repo -- but DON'T PUSH!
  * [x] Change all references of docs3.lfe.io to docs.lfe.io
  * [x] Place deprecation notice on docs3 repo (we'll still want to keep it around, due to the tickets, etc. that exist in it)
  * [x] Re-gen latest content (should be ready after merge; but it's a good test to run again)
  * [x] Push new master branch to Github
  * [x] Update the docs repo to use `docs` dir for publishing and not `gh-pages` branch (this is a Github "Settings" change)

Part of Milestone v3  #62

**Comment by oubiwann** [comment]
Phew!!! THIS MONSTER IS DONE.
