### ISSUE TITLE
Produce v3.1 of the LFE Docs Site

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#95]
The work on the LFE docs site continues, carried over from [v3.0](https://github.com/lfe/docs/issues/62).

This work maintains the same goals as the v3.0 release:

- Provide a usable site-generating infrastructure (tools and procedures) for docs contributors
- Produce a clean, easy-to-navigate site that is the single source of truth for all LFE docs, regardless of where the bits actually live.
- Maintain versioned docs so that those who are stuck using older versions of LFE and/or Erlang are supported (to the extent that docs existed when their chosen version was released).

To do this, a great deal of work is necessary. The major categories of this work are represented by the tickets listed below, each with their own tasks and/or supporting tickets:

- [ ] Look and Feel - #96
- [ ] Unification of Disparate Content - #97
- [ ] Guidelines for Individual Projects - #70
- [ ] Add Missing Content - #75
- [ ] Revamp Old Content - #98
- [ ] Infrastructure Updates - #102

**Comment by oubiwann** [comment]
We're going to ditch the docs site with all serious content going into LFE books, and general docs content going to lfe.io/docs
