### ISSUE TITLE
Unification of Disparate Content

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs#97]
This epic is continuation of the v3.0 epic: #69

All of the various forms of documentation identified in ticket #63 need to be brought into the fold:

- [ ] Pull in new Markdown docs from official LFE repo
- [ ] Convert/integrate old content from docs.lfe.io (needs ticket)
- [ ] Pull in selected Erlang stdlib HTML docs and integrate as part of the whole - #73
- [ ] Pull in Markdown from Gitbooks

Part of release #95

**Comment by oubiwann** [comment]
We're going to ditch the docs site with all serious content going into LFE books, and general docs content going to lfe.io/docs
